### PR TITLE
Improve handling of nulls and blobs in binary fields

### PR DESCRIPTION
**Pull request by nshahquinn**
Previously, a null value in a binary-encoded MariaDB field would cause an
AttributeError. These are rare in our infrastructure since MediaWiki generally
uses empty strings instead.

I had assumed that MediaWiki did not use blob fields, but it turns out they
are very common. In all the cases I found, the fields contain UTF-8 string
data, so these are now decoded as well.

### CODE REVIEW

**Comment by nshahquinn** [comment]
Just verified that this passes the test suite.

**Comment by nshahquinn** [comment]
After I noticed the null value problem, I went diving through lots of different MariaDB tables looking for other cases that weren't being handled properly. That's how I realized that there were actually lots of blob fields. So, _hopefully_, now that I've gone looking, I've found all the substantial issues in this area.

**Review by nettrom — CHANGES_REQUESTED** [review]
I don't get this to pass testing. From what I can tell, any integer column (e.g. `content_edits` in `wmfdata_test`, `user_editcount` in `user`) that has a value of `0` results in a `NaN`, and so the MariaDB equality test fails (on `content_edits` rows 6 and 10 in `wmfdata_test`).

It look like this happens because the call in line 37 to `super().to_python()` results in a match on the if-statement in https://github.com/mysql/mysql-connector-python/blob/master/lib/mysql/connector/conversion.py#L190, and so a `None` is returned from that method. If I comment out line 94 so `ByteConverter` isn't used, zero-value integers are returned correctly.

Passing conversion up to the superclass seems like the intuitive thing to do. I'm not sure if the superclass expects us to identify the returned column types and call their respective methods rather than expect `to_python()` to behave in a more reasonable way.

**Comment by nshahquinn** [comment]
> I don't get this to pass testing. From what I can tell, any integer column (e.g. `content_edits` in `wmfdata_test`, `user_editcount` in `user`) that has a value of `0` results in a `NaN`, and so the MariaDB equality test fails (on `content_edits` rows 6 and 10 in `wmfdata_test`).
>
> It look like this happens because the call in line 37 to `super().to_python()` results in a match on the if-statement in https://github.com/mysql/mysql-connector-python/blob/master/lib/mysql/connector/conversion.py#L190, and so a `None` is returned from that method. If I comment out line 94 so `ByteConverter` isn't used, zero-value integers are returned correctly.

Okay, wow! This is confusing. I didn't see this with my installation, with mysql-connector-python 8.0.28. However, I replicated what you saw after switching to a brand-new environment, with mysql-connector-python 8.0.23.

It's not immediately clear why the behavior is so different; both version have the line you identified as the culprit. The only change to `conversion.py` between the two versions was the [one which set off this string of MariaDB patches](https://github.com/mysql/mysql-connector-python/commit/82764da6cb062eb890e311049e700315a190a9f8), so it's almost certainly responsible. I spent almost an hour trying to figure out exactly how, but I gave up after reflecting that it doesn't matter since it's easy enough to require the newer version of mysql-connector-python.

I'll push that change up now; hopefully it works for you!

**Comment by nshahquinn** [comment]
Okay, I hadn't actually pushed the change (maybe I should add commits to the branch instead of amending one commit like I would on Gerrit). But _now_ I have.

**Comment by nshahquinn** [comment]
Thank you very much @milimetric!

It's not a big deal at all, but when you have an unrelated change to make, I suggest making a separate PR or commit. In this case, since it was a documentation improvement that didn't touch code, I think you can just make a separate commit directly to the master branch, without making a PR and having it review 😊

**Comment by nshahquinn** [comment]
> It's not a big deal at all, but when you have an unrelated change to make, I suggest making a separate PR or commit. In this case, since it was a documentation improvement that didn't touch code, I think you can just make a separate commit directly to the master branch, without making a PR and having it review 😊

Oh, I see from your messages on Slack that it's related to getting the right version of mysql-connector-python installed. That makes sense, then. Ignore me 😊

**Comment by milimetric** [comment]
I would've honestly put it in a different PR but for some reason the way I
did it forced it into this one.  Github is a magical place.

**Pull request merged**
