### PR TITLE
Suppress Pandas UserWarning during mariadb.run and hive.run

### PR DESCRIPTION
**Pull request by jsnshrmn**
Filters UserWarnings with pandas SQLAlchemy message

Note that I wasn't able to test directly as I couldn't successfully install my own version of this library to my environment on a stathost. But this filter approach is what I used in my own code to wrap the provided `run()` methods

Bug: [T324135](https://phabricator.wikimedia.org/T324135)

### CODE REVIEW

**Comment by nshahquinn** [comment]
Thank you so much for contributing @jsnshrmn! I've given it a quick look and the only request I have is that you add a short comment in both locations with a brief explanation and the task number for future reference.

I've given it a quick test locally and it works as advertised! I'll come back tomorrow and run the full test suite.

> Note that I wasn't able to test directly as I couldn't successfully install my own version of this library to my environment on a stathost

Could you share more about the problems you encountered? Maybe we can figure it out and make it easier for the next person 😊

**Comment by nshahquinn** [comment]
I ran the test suite and everything works great. I also added the comments myself just because I'm about to do a release as part of [migrating this repo to GitLab](https://phabricator.wikimedia.org/T304544) and I want to get this improvement in.

Thank you so much @jsnshrmn and I'm excited for your next contribution 😁

**Comment by jsnshrmn** [comment]
Oopsie, I was just a little too slow; I reworked this into a decorator thinking that might be a bit cleaner. Either way works though!
https://github.com/wikimedia/wmfdata-python/compare/main...jsnshrmn:wmfdata-python:Jsn.sherman/T324135

**Comment by jsnshrmn** [comment]
oh, and the error I was getting on the stat host was network related:
```
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3dd35b8190>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3dd35b8ac0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3dd35b8d30>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3dd35b8e20>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3dd35b8fa0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
```

**Comment by nshahquinn** [comment]
> Oopsie, I was just a little too slow; I reworked this into a decorator thinking that might be a bit cleaner. Either way works though!

Ooh, the rewards of patience! The decorator is even better and I want to get that merged too. I'll open up a new PR and do a quick review there.

> oh, and the error I was getting on the stat host was network related

Hmm, did you have the [HTTP proxy](https://wikitech.wikimedia.org/wiki/HTTP_proxy) set? This gets done automatically if you're using [the hosted Jupyter](https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Jupyter), but otherwise you have to do it manually.

**Comment by jsnshrmn** [comment]
> > Oopsie, I was just a little too slow; I reworked this into a decorator thinking that might be a bit cleaner. Either way works though!
> 
> Ooh, the rewards of patience! The decorator is even better and I want to get that merged too. I'll open up a new PR and do a quick review there.

I went ahead and updated the commit to actually make sense after the rebase.
> 
> > oh, and the error I was getting on the stat host was network related
> 
> Hmm, did you have the [HTTP proxy](https://wikitech.wikimedia.org/wiki/HTTP_proxy) set? This gets done automatically if you're using [the hosted Jupyter](https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Jupyter), but otherwise you have to do it manually.

I did not! Thanks!

**Pull request merged**
