### PR TITLE
Remove code handling now-removed anaconda-wmf environments

### PR DESCRIPTION
**Pull request by nshahquinn**
Bug: [T346707](https://phabricator.wikimedia.org/T346707)

### CODE REVIEW

**Comment by nshahquinn** [comment]
I don't consider this a blocker for merging but this code creates one oddity which bugs me. Please let me if you have any insights!

This commit causes a new warning message (almost invisible in the torrent of logspam) to appear in the output when you run `wmfdata_tests/tests.py`:
```
...
TEST PASSED: Spark Session APIs
usage: tests.py [-h] hive_database
tests.py: error: unrecognized arguments: --all --json
...
[Spark session startup logspam]
...
TEST PASSED: Read via Spark      
```

This makes it seem like something is going wrong inside `test_read_via_spark` with a call to `conda.info()`, which includes `condacli("info", ["--all", "--json"]`. But I have no idea how `conda.info` might get called or why it would cause that warning message even if it did (since the function works fine on its own).

I could not replicate this by running the code from `test_read_via_spark` both in a notebook and in a Python script, which underscores that this is not an actual problem.

But, still, super weird, and I'd feel great if anyone else managed to figure it out!

**Review by xabriel — APPROVED** [review]
LGTM!

**Comment by xabriel** [comment]
> This commit causes a new warning message (almost invisible in the torrent of logspam) to appear in the output when you run `wmfdata_tests/tests.py`:

So you tried running the tests without the changes from this MR and you could not repro?

> This makes it seem like something is going wrong inside `test_read_via_spark` with a call to `conda.info()`, which includes `condacli("info", ["--all", "--json"]`. But I have no idea how `conda.info` might get called or why it would cause that warning message even if it did (since the function works fine on its own).

We don't pin `conda` on this repo, but we do pin it downstream in `conda_analytics`, so perhaps the API changed.

**Comment by nshahquinn** [comment]
@xabriel thank you for the speedy review!

> So you tried running the tests without the changes from this MR and you could not repro?

Yes, exactly. If I switch back to the previous commit, leaving everything else the same, and run the tests again, I don't get the message.

**Pull request merged**
